CREATE TABLE vehicle(
	VEHICLEID NUMBER(18) NOT NULL,
	vin VARCHAR2(32) NOT NULL,
	model VARCHAR2(32) NOT NULL,
	make VARCHAR2(32) NOT NULL,
	year NUMBER(4) NOT NULL,
	miles NUMBER(10) NULL,
CONSTRAINT chk_vehicle_year_gt_2005
    			CHECK (year> 2004),
CONSTRAINT chk_vehicle_miles_lt_10001
    			CHECK (miles< 10001));
CREATE UNIQUE INDEX uidx_vehicle_vin
    			ON  vehicle(vin);

ALTER TABLE VEHICLE ADD CONSTRAINT
			pk_vehicle PRIMARY KEY (VEHICLEID);

CREATE SEQUENCE S_VEHICLE
    START WITH 10000000
    INCREMENT BY 1
;

--//@UNDO
DROP TABLE VEHICLE;
DROP SEQUENCE S_VEHICLE